### PR TITLE
FIX: removed addition operator that prevented whitespace matching

### PR DESCRIPTION
**Pull request by hnb-ku**
More here: https://meta.discourse.org/t/add-abbr-tags-to-words-in-posts/88394/7

### CODE REVIEW

**Comment by Freso** [comment]
@hnb-ku I'm happy to merge either this or https://github.com/metabrainz/discourse-abbrify-words/pull/2 – would you be happy with the approach from https://github.com/metabrainz/discourse-abbrify-words/pull/2 over the approach you've taken here?

(Also, sorry about the review delay!)

**Comment by jesus2099** [comment]
Technically, it could work if we applied #1 then #2.
Would be same result as only #2 but without denying #1 from history.

**Comment by danielhollas** [comment]
I've recently addressed this issue a bit more comprehensively in the original auto-linkify theme in [this PR](https://github.com/discourse/discourse-linkify-words/pull/2). There was [some discussion on META](https://meta.discourse.org/t/linkify-words-in-post/82193/58?u=danekhollas) about which characters should be the boundary characters.

My approach should cover most cases as in #2, although it is a bit more conservative. @Freso I am happy to port those changes and make a new PR if you wish or you could also simply copy those three lines from that PR.

**Comment by danielhollas** [comment]
Also FYI: Since then, @hnb-ku merged another small fix in auto-linkify to strip white space in from settings list. I wonder whether in the end it wouldn't be easier to merge these two themes, given how much code they share...but that's probably better to discuss on meta.

In any case, thanks @jesus2099 for making this, I am adding it to my site now, it is exactly what I was looking for. :+1:

**Comment by hnb-ku** [comment]
@Freso 

#1 focuses on stripping out whitespace in abbreviation.
#2 also does that but also extends matching to include punctuation. 

@jesus2099 seems to have already tested the changes proposed in #2 so I have no problem with closing / skipping #1 and going with #2

**Comment by Freso** [comment]
Thanks @hnb-ku - merged in https://github.com/metabrainz/discourse-abbrify-words/pull/2 now. :)

**Pull request closed without merging**
